name: Deploy Flask App

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python and Git
      run: |
        sudo yum update -y
        sudo yum install python3 git -y
        python3 -m pip install --upgrade pip

    - name: Set up virtual environment
      run: |
        python3 -m venv /media/my_services/venv
        source /media/my_services/venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          source /media/my_services  # Load environment variables
          source /media/my_services/venv/bin/activate  # Activate virtual environment
          cd /media/my_services
          git pull origin main
          python main.py
