name: Deploy Flask App

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Print Current Directory
      run: |
        pwd

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python and Git
      run: |
        sudo apt update -y
        sudo apt install python3 git -y
        python3 -m pip install --upgrade pip

    - name: Print Current Directory 1
      run: |
        pwd

    - name: Set up virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          pwd
          source /home/runner/work/my_portfolio_backend/my_portfolio_backend  # Load environment variables
          source /home/runner/work/my_portfolio_backend/my_portfolio_backend/venv/bin/activate  # Activate virtual environment
          cd /home/runner/work/my_portfolio_backend/my_portfolio_backend
          git pull origin main
          python main.py
