name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1  # Replace with your region

      - name: Upload SSH key
        uses: actions/upload-artifact@v3
        with:
          name: ssh-key

      - name: Download SSH key
        run: |
          mkdir deploy-key
          mv ~/artifacts/ssh-key/*.ppk deploy-key/id_rsa
          chmod 600 deploy-key/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i deploy-key/id_rsa ec2-user@18.205.156.224 \
             ./deploy.sh

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
