name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Add EC2 Host to Known Hosts
      run: |
        ssh-keyscan -H 44.203.137.82 >> ~/.ssh/known_hosts

    - name: Copy files to EC2
      run: scp -o StrictHostKeyChecking=no -r . root@$44.203.137.82:/home/ec2-user/mongodb

    - name: SSH into EC2 and deploy
      run: |
        ssh -o StrictHostKeyChecking=no root@$44.203.137.82 << 'EOF'
          cd /home/ec2-user/my_portfolio_backend
          sudo docker-compose down
          sudo docker-compose up --build -d
        EOF
